### ISSUE TITLE
question about REM baseline implementation

### ISSUE THREAD

**Issue by Howuhh** [snu-mllab/EDAC#2]
Hi! Really puzzled by the REM performance as it is a bit counterintuitive that it does not actually work at all but very similar to SAC-N in theory! The appendix doesn't say how the ensemble was implemented and I don't see it in the code. So, I decided to ask if separate nets were used for the ensemble or just different heads with shared first layers as in original REM paper?

Thanks!

**Comment by symoon11** [comment]
Hi. It is worth noting that REM takes a random convex combination of Q-network outputs to compute Q-values and their Bellman targets, while SAC-N takes the minimum of Q-network outputs to compute Bellman targets. Taking the minimum is crucial to achieving good performance in offline RL while preventing the explosion of the Q-values. We ran REM with separate Q-networks (multi-network REM) since it has demonstrated superior results compared to multi-head REM.

**Comment by Howuhh** [comment]
Thanks!
